// Curated word pools for auto-generated player display names.
// Style: short, neutral, family-friendly, easy to remember when read aloud.
// Both lists are intentionally lowercase and dash-safe.

export const ADJECTIVES = [
  "amber", "ample", "ancient", "april", "arctic", "ashen", "autumn", "azure",
  "balmy", "blazing", "blithe", "bold", "boreal", "brave", "breezy", "bright",
  "brisk", "bronze", "calm", "candid", "casual", "cedar", "cheery", "cherry",
  "civic", "clever", "cloudy", "coastal", "cobalt", "cool", "copper", "cosmic",
  "cozy", "crisp", "crystal", "daring", "dawn", "deft", "dewy", "distant",
  "dreamy", "dusty", "earnest", "easy", "eerie", "electric", "ember", "fabled",
  "faint", "fair", "feisty", "fern", "fierce", "flaxen", "fluid", "fond",
  "forest", "fresh", "frosty", "gallant", "gentle", "ginger", "glacial",
  "glassy", "golden", "graceful", "grand", "happy", "hardy", "hazel", "heady",
  "hidden", "honest", "humble", "icy", "indigo", "inland", "ivory", "jade",
  "jaunty", "jolly", "joyful", "kind", "lace", "lake", "lavender", "lazy",
  "lean", "lemon", "lilac", "lithe", "lively", "lofty", "loyal", "lucid",
  "lucky", "lunar", "lush", "marble", "marine", "meadow", "merry", "midnight",
  "mighty", "mild", "minty", "misty", "modest", "mossy", "muted", "neon",
  "nimble", "noble", "northern", "oaken", "ocean", "olive", "opal", "orchid",
  "pacific", "patient", "peach", "pearl", "perky", "pine", "placid", "plucky",
  "polar", "polite", "prairie", "prompt", "proud", "quaint", "quick", "quiet",
  "radiant", "rapid", "ready", "regal", "ripple", "river", "rosy", "ruby",
  "rugged", "rustic", "sage", "salty", "sandy", "saucy", "scarlet", "scenic",
  "secret", "serene", "shady", "sharp", "silent", "silken", "silver", "simple",
  "sleek", "slim", "smooth", "snowy", "solar", "solid", "sonic", "sparkling",
  "spicy", "spry", "stalwart", "starry", "steady", "stoic", "stormy", "subtle",
  "summer", "sunlit", "sunny", "swift", "tame", "tangy", "tart", "tender",
  "thrifty", "tidy", "tiger", "topaz", "tranquil", "true", "twilight", "umber",
  "unique", "urban", "valiant", "velvet", "verdant", "vibrant", "vivid",
  "warm", "wary", "weathered", "whimsical", "wild", "windy", "winged", "winter",
  "wise", "witty", "woody", "woven", "yellow", "young", "zesty",
];

export const NOUNS = [
  "acorn", "albatross", "alpaca", "anchor", "antelope", "apricot", "aspen",
  "badger", "bamboo", "barley", "basalt", "beacon", "beaver", "beetle",
  "birch", "bison", "blossom", "bluebird", "bobcat", "boomerang", "boulder",
  "branch", "breeze", "buckeye", "bumblebee", "burrow", "butterfly", "cactus",
  "canyon", "cardinal", "caribou", "cascade", "cedar", "chameleon", "cheetah",
  "chestnut", "chickadee", "cinder", "clam", "clover", "comet", "compass",
  "coral", "cottage", "cougar", "coyote", "crocus", "cypress", "daisy",
  "dewdrop", "dolphin", "dragonfly", "dune", "eagle", "eclipse", "egret",
  "elder", "elk", "ember", "falcon", "fawn", "fern", "ferret", "finch",
  "firefly", "fjord", "flamingo", "fossil", "fox", "frog", "gander", "gazelle",
  "geode", "geyser", "ginger", "glade", "glider", "goose", "gopher", "granite",
  "grebe", "grouse", "gull", "harbor", "harvest", "hawk", "hazel", "heron",
  "hickory", "horizon", "hornet", "hummingbird", "iceberg", "iguana", "iris",
  "jackal", "jaguar", "jasmine", "jay", "juniper", "katydid", "kestrel",
  "kingfisher", "kiwi", "koala", "lagoon", "lantern", "larch", "lark", "lemur",
  "leopard", "lily", "lion", "lobster", "lupine", "lynx", "magnolia", "mallard",
  "manta", "maple", "marigold", "marlin", "marmot", "marsh", "meadowlark",
  "meerkat", "minnow", "mockingbird", "mole", "monsoon", "moose", "mosaic",
  "moth", "narwhal", "nettle", "newt", "nightjar", "nimbus", "nuthatch",
  "oasis", "ocelot", "olive", "opal", "orca", "orchid", "osprey", "otter",
  "owl", "panda", "panther", "parrot", "peach", "pebble", "pelican", "penguin",
  "petal", "phoenix", "pier", "pigeon", "pine", "plover", "polestar", "pony",
  "poplar", "prairie", "puffin", "quail", "quartz", "quokka", "raccoon", "raven",
  "redwood", "reef", "rhino", "ridge", "ripple", "robin", "rooster", "saffron",
  "salmon", "sandpiper", "sapphire", "sequoia", "shoreline", "skylark", "sloth",
  "snowdrop", "sparrow", "starling", "stoat", "summit", "swallow", "swan",
  "tamarin", "tapir", "tern", "thicket", "thrush", "thunder", "tide", "topaz",
  "trout", "tulip", "tundra", "turtle", "twig", "valley", "vine", "vireo",
  "vole", "walrus", "warbler", "wavecrest", "weaver", "willow", "wisp",
  "wolverine", "woodpecker", "wren", "yarrow", "zebra", "zinnia",
];
