export const CATEGORY_ORDER = ["all", "tech", "politics", "sports", "celebrities", "random"];

export const LANGUAGES = [
  {
    id: "en",
    name: "English",
    nativeName: "English",
    instruction: "Write natural English with internet-native phrasing.",
  },
  {
    id: "es",
    name: "Spanish",
    nativeName: "Español",
    instruction: "Write natural Spanish with internet-native phrasing.",
  },
  {
    id: "fr",
    name: "French",
    nativeName: "Français",
    instruction: "Write natural French with internet-native phrasing.",
  },
  {
    id: "pt",
    name: "Portuguese",
    nativeName: "Português",
    instruction: "Write natural Portuguese with internet-native phrasing.",
  },
  {
    id: "de",
    name: "German",
    nativeName: "Deutsch",
    instruction: "Write natural German with internet-native phrasing.",
  },
];
export const DEFAULT_LANGUAGE = "en";
export const LANGUAGE_ORDER = LANGUAGES.map((language) => language.id);

export const CATEGORY_META = {
  all: {
    name: "All Signals",
    blurb: "A mixed feed of every loud internet persona.",
    accent: "#f3ca59",
    soft: "rgba(243, 202, 89, 0.18)",
    heroTitle: "Mixed-feed mayhem for terminally online guessers.",
  },
  tech: {
    name: "Tech",
    blurb: "Founders, AI prophets, code streamers, and terminal monks.",
    accent: "#ff7445",
    soft: "rgba(255, 116, 69, 0.18)",
    heroTitle: "Startup fumes, infra panic, and AI sermons.",
  },
  politics: {
    name: "Politics",
    blurb: "Campaign operatives, committee sickos, and polling mystics.",
    accent: "#59abff",
    soft: "rgba(89, 171, 255, 0.18)",
    heroTitle: "Coalition math, committee knives, and endless certainty.",
  },
  sports: {
    name: "Sports",
    blurb: "Legacy wars, cap-sheet theology, and replay courtroom drama.",
    accent: "#48d69b",
    soft: "rgba(72, 214, 155, 0.18)",
    heroTitle: "Banner talk, fake trades, and officiating litigation.",
  },
  celebrities: {
    name: "Celebrities",
    blurb: "Publicists, pop stans, red carpets, and apology-note handwriting analysis.",
    accent: "#d6482a",
    soft: "rgba(214, 72, 42, 0.18)",
    heroTitle: "Notes-app diplomacy and fame-cycle meteorology.",
  },
  random: {
    name: "Random People",
    blurb: "HOA veterans, airport philosophers, recipe commenters, and neighborhood lore.",
    accent: "#0e1f3a",
    soft: "rgba(14, 31, 58, 0.18)",
    heroTitle: "The common poster, operating at uncommon volume.",
  },
};

export const MODELS = [
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    blurb: "Snappy, meme-literate, and a little too clean when it lands a joke.",
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    blurb: "Balanced phrasing, polished cadence, and a suspiciously tidy rhythm.",
  },
  {
    id: "gemini-2-0-flash",
    name: "Gemini 2.0 Flash",
    blurb: "Fast, assertive, and sometimes just a touch extra for no reason.",
  },
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B",
    blurb: "Open-weights swagger with longer phrasing and louder confidence.",
  },
  {
    id: "deepseek-v3-2",
    name: "DeepSeek V3.2",
    blurb: "Cheap, direct, and sharper than its token price should allow.",
  },
];

export const AUTHORS = [
  {
    id: "alignment-monarch",
    category: "tech",
    name: "Sam Altman",
    handle: "@sama",
    bio: "OpenAI CEO whose posts can swing from civilization-scale AI thoughts to product-launch calm.",
    signature: "Earnest AGI destiny, boardroom weather, and suspiciously crisp product timing. Parody, not a real post.",
  },
  {
    id: "vim-arsonist",
    category: "tech",
    name: "ThePrimeagen",
    handle: "@ThePrimeagen",
    bio: "Streamer and engineer known for loud, fast, deeply opinionated programming takes.",
    signature: "Keyboard velocity, compiler yelling, and zero patience for framework etiquette. Parody, not a real post.",
  },
  {
    id: "theo-coded-sermon",
    category: "tech",
    name: "Theo",
    handle: "@theo",
    bio: "T3 creator and stack-discourse magnet with strong opinions about shipping web software.",
    signature: "Fast takes, stack conviction, and a faint smell of deployment adrenaline. Parody, not a real post.",
  },
  {
    id: "txdr-terminal",
    category: "tech",
    name: "TJ DeVries",
    handle: "@teej_dv",
    bio: "Neovim core maintainer and terminal maximalist with a taste for sharp systems ergonomics.",
    signature: "Systems minimalism, terminal romance, and refusal to let the mouse win. Parody, not a real post.",
  },
  {
    id: "cloud-gremlin",
    category: "tech",
    name: "DHH",
    handle: "@dhh",
    bio: "Rails creator and Basecamp cofounder with strong views on software, cloud spend, and complexity.",
    signature: "Infra skepticism, simplicity religion, and intense feelings about operational discipline. Parody, not a real post.",
  },
  {
    id: "productivity-baron",
    category: "tech",
    name: "Pieter Levels",
    handle: "@levelsio",
    bio: "Indie hacker known for shipping small internet businesses in public.",
    signature: "Solo shipping, blunt metrics, and a deep suspicion of meetings. Parody, not a real post.",
  },
  {
    id: "poll-whisperer",
    category: "politics",
    name: "Nate Silver",
    handle: "@NateSilver538",
    bio: "Statistician and election forecaster who can make a crosstab feel like a weather system.",
    signature: "Everything is a probability story once the crosstabs drop. Parody, not a real post.",
  },
  {
    id: "committee-hawk",
    category: "politics",
    name: "C-SPAN",
    handle: "@cspan",
    bio: "Public affairs network whose feed turns procedure into the main character.",
    signature: "If the drama is inside the amendment tree, this is the habitat. Parody, not a real post.",
  },
  {
    id: "debate-clip-cartographer",
    category: "politics",
    name: "Aaron Rupar",
    handle: "@atrupar",
    bio: "Political clip-watcher and newsletter writer who tracks the televised weirdness beat.",
    signature: "Clip analysis, body-language prophecy, and aggressive context windows. Parody, not a real post.",
  },
  {
    id: "flag-pin-maximalist",
    category: "politics",
    name: "Alexandria Ocasio-Cortez",
    handle: "@AOC",
    bio: "Congresswoman with a direct-to-feed style for policy fights and political framing.",
    signature: "Moral clarity, message discipline, and no patience for fake process objections. Parody, not a real post.",
  },
  {
    id: "city-hall-goblin",
    category: "politics",
    name: "Matt Yglesias",
    handle: "@mattyglesias",
    bio: "Policy writer whose feed can turn zoning, abundance, and institutions into daily combat.",
    signature: "Local procedural warfare with highly specific civic grievances. Parody, not a real post.",
  },
  {
    id: "beltway-brunchlord",
    category: "politics",
    name: "Jake Tapper",
    handle: "@jaketapper",
    bio: "CNN anchor and political journalist with a classic Beltway news cadence.",
    signature: "Green-room gravity, source choreography, and ceremonial moderation. Parody, not a real post.",
  },
  {
    id: "ring-counter",
    category: "sports",
    name: "LeBron James",
    handle: "@KingJames",
    bio: "NBA star whose posts can turn hoops, legacy, and culture into one timeline event.",
    signature: "Legacy math, banner pressure, and a crown emoji implied even when absent. Parody, not a real post.",
  },
  {
    id: "cap-space-shaman",
    category: "sports",
    name: "Shams Charania",
    handle: "@ShamsCharania",
    bio: "NBA insider whose posts make transactions feel like emergency alerts.",
    signature: "Contract arithmetic, source phrasing, and trade-machine transcendence. Parody, not a real post.",
  },
  {
    id: "locker-room-poet",
    category: "sports",
    name: "Stephen A. Smith",
    handle: "@stephenasmith",
    bio: "Sports broadcaster whose feed favors volume, certainty, and theatrical urgency.",
    signature: "Vibes, chemistry, and emotional weather over sterile counting stats. Parody, not a real post.",
  },
  {
    id: "instant-replay-dad",
    category: "sports",
    name: "Bill Simmons",
    handle: "@BillSimmons",
    bio: "Sports and pop-culture podcaster with a bottomless appetite for legacy hypotheticals.",
    signature: "Rulebook obsession, slow-motion outrage, and podcast-era grievance math. Parody, not a real post.",
  },
  {
    id: "pop-pr-crisis-manager",
    category: "celebrities",
    name: "Taylor Swift",
    handle: "@taylorswift13",
    bio: "Pop megastar whose announcements can reroute the entire entertainment timeline.",
    signature: "Release strategy, fan decoding, and immaculate rollout weather. Parody, not a real post.",
  },
  {
    id: "red-carpet-forensicist",
    category: "celebrities",
    name: "Rihanna",
    handle: "@rihanna",
    bio: "Artist and founder whose rare posts make the whole internet inspect timing and subtext.",
    signature: "Beauty empire signals, publicist tea leaves, and suspiciously confident timing reads. Parody, not a real post.",
  },
  {
    id: "stan-account-general",
    category: "celebrities",
    name: "MrBeast",
    handle: "@MrBeast",
    bio: "Creator whose posts make giveaways, video scale, and platform experiments feel like sport.",
    signature: "Platform math, spectacle logistics, and an alarming number of zeroes. Parody, not a real post.",
  },
  {
    id: "nepo-baby-apologist",
    category: "celebrities",
    name: "Kim Kardashian",
    handle: "@KimKardashian",
    bio: "Celebrity founder whose posts sit at the intersection of image, commerce, and spectacle.",
    signature: "Brand architecture, tasteful lighting, and a suspicious respect for launch timing. Parody, not a real post.",
  },
  {
    id: "hoa-nightmare",
    category: "random",
    name: "dril",
    handle: "@dril",
    bio: "Legendary Weird Twitter account whose posts turn institutional collapse into nonsense scripture.",
    signature: "Petty governance, broken logic, and absolute commitment to the bit. Parody, not a real post.",
  },
  {
    id: "airport-gate-prophet",
    category: "random",
    name: "Internet Hippo",
    handle: "@InternetHippo",
    bio: "Internet humor account with concise, dry observations about ordinary social absurdity.",
    signature: "Tiny social autopsies, institutional suspicion, and dry refusal to over-explain. Parody, not a real post.",
  },
  {
    id: "recipe-commenter",
    category: "random",
    name: "Depths of Wikipedia",
    handle: "@depthsofwiki",
    bio: "Internet account surfacing strange Wikipedia corners and delightful niche facts.",
    signature: "Citation rabbit holes, one-sentence lore, and trivia with a backstory. Parody, not a real post.",
  },
  {
    id: "neighborhood-app-detective",
    category: "random",
    name: "SwiftOnSecurity",
    handle: "@SwiftOnSecurity",
    bio: "Security-focused internet account mixing enterprise caution with deadpan absurdity.",
    signature: "Doorbell-camera noir, enterprise paranoia, and very high confidence. Parody, not a real post.",
  },
];

export const POSTS = [
  {
    id: "tech-1",
    category: "tech",
    authorId: "alignment-monarch",
    modelId: "deepseek-v3-2",
    text: "The correct AI policy is to slow down, coordinate globally, and also please try our new agent runtime before the waitlist closes.",
  },
  {
    id: "tech-2",
    category: "tech",
    authorId: "alignment-monarch",
    modelId: "claude-3-5-haiku",
    text: "People keep asking if the model is conscious. I am asking why the demo still needs three product managers and a launch embargo.",
  },
  {
    id: "tech-3",
    category: "tech",
    authorId: "vim-arsonist",
    modelId: "gpt-4o-mini",
    text: "I deleted the abstraction and the app got faster, uglier, and spiritually honest. This is what senior engineering looks like.",
  },
  {
    id: "tech-4",
    category: "tech",
    authorId: "vim-arsonist",
    modelId: "llama-3-3-70b",
    text: "Your framework is not bad because it is slow. It is bad because it makes mediocrity feel like a component library.",
  },
  {
    id: "tech-5",
    category: "tech",
    authorId: "theo-coded-sermon",
    modelId: "gemini-2-0-flash",
    text: "The stack debate is simple: if your deploy story needs a campfire, a priest, and twelve environment variables, pick something else.",
  },
  {
    id: "tech-6",
    category: "tech",
    authorId: "theo-coded-sermon",
    modelId: "deepseek-v3-2",
    text: "Nobody hates your favorite framework. We just noticed it turned a button into a governance problem.",
  },
  {
    id: "tech-7",
    category: "tech",
    authorId: "txdr-terminal",
    modelId: "claude-3-5-haiku",
    text: "The terminal is not retro. It is the last honest room in computing and I will not be taking questions from dropdown enthusiasts.",
  },
  {
    id: "tech-8",
    category: "tech",
    authorId: "txdr-terminal",
    modelId: "gpt-4o-mini",
    text: "Every GUI eventually becomes a worse TUI with shadows. I am simply arriving early and refusing the onboarding modal.",
  },
  {
    id: "tech-9",
    category: "tech",
    authorId: "cloud-gremlin",
    modelId: "claude-3-5-haiku",
    text: "Nothing reveals character faster than how a team reacts to a 2:13 a.m. multi-region incident.",
  },
  {
    id: "tech-10",
    category: "tech",
    authorId: "cloud-gremlin",
    modelId: "gpt-4o-mini",
    text: "The database did not randomly go down. Someone treated observability like a personality trait instead of a budget item.",
  },
  {
    id: "tech-11",
    category: "tech",
    authorId: "productivity-baron",
    modelId: "llama-3-3-70b",
    text: "The first hour of the day belongs to caffeine, silence, and deleting meetings from weaker people's calendars.",
  },
  {
    id: "tech-12",
    category: "tech",
    authorId: "productivity-baron",
    modelId: "gemini-2-0-flash",
    text: "Inbox zero is not productivity. True productivity is making sure nobody can schedule time with you in the first place.",
  },
  {
    id: "politics-1",
    category: "politics",
    authorId: "poll-whisperer",
    modelId: "claude-3-5-haiku",
    text: "The election is not being decided by the loudest people online. It is being decided by a county you have only seen in crosstab PDFs.",
  },
  {
    id: "politics-2",
    category: "politics",
    authorId: "poll-whisperer",
    modelId: "gpt-4o-mini",
    text: "Every candidate says they are building a coalition. Show me one suburban bloc and two turnout assumptions and then we can talk.",
  },
  {
    id: "politics-3",
    category: "politics",
    authorId: "committee-hawk",
    modelId: "llama-3-3-70b",
    text: "If you think the headline matters more than the committee markup, you are not following where the real knives are.",
  },
  {
    id: "politics-4",
    category: "politics",
    authorId: "committee-hawk",
    modelId: "gemini-2-0-flash",
    text: "The amendment failed 11-10, which means congratulations, the staff memo has more power than your entire group chat.",
  },
  {
    id: "politics-5",
    category: "politics",
    authorId: "debate-clip-cartographer",
    modelId: "deepseek-v3-2",
    text: "That seven-second stumble was either fatal or meaningless, depending entirely on which county-level turnout model validates my personality.",
  },
  {
    id: "politics-6",
    category: "politics",
    authorId: "debate-clip-cartographer",
    modelId: "gpt-4o-mini",
    text: "The hand gesture at 12:41 tells us nothing, which is why I have prepared a thread with nine maps.",
  },
  {
    id: "politics-7",
    category: "politics",
    authorId: "flag-pin-maximalist",
    modelId: "gpt-4o-mini",
    text: "This nation was built by people who did not ask permission to lead, and frankly neither is my preferred candidate.",
  },
  {
    id: "politics-8",
    category: "politics",
    authorId: "flag-pin-maximalist",
    modelId: "llama-3-3-70b",
    text: "You can keep your nuance. I am interested in strength, momentum, and a camera angle with at least three flags in frame.",
  },
  {
    id: "politics-9",
    category: "politics",
    authorId: "city-hall-goblin",
    modelId: "gemini-2-0-flash",
    text: "The most dangerous person in municipal politics is not the mayor. It is the resident who knows how public comment rules actually work.",
  },
  {
    id: "politics-10",
    category: "politics",
    authorId: "city-hall-goblin",
    modelId: "claude-3-5-haiku",
    text: "Tonight's council agenda is 417 pages, which means somewhere around item 63 a neighborhood feud becomes housing policy.",
  },
  {
    id: "politics-11",
    category: "politics",
    authorId: "beltway-brunchlord",
    modelId: "deepseek-v3-2",
    text: "Several people who would benefit from this being true have told me privately that the vibes are shifting.",
  },
  {
    id: "politics-12",
    category: "politics",
    authorId: "beltway-brunchlord",
    modelId: "gemini-2-0-flash",
    text: "The lunch was off record, but the salad placement said more than any spokesperson could.",
  },
  {
    id: "sports-1",
    category: "sports",
    authorId: "ring-counter",
    modelId: "gpt-4o-mini",
    text: "I do not care about the efficiency case. Show me who closes in June when the banners are not theoretical.",
  },
  {
    id: "sports-2",
    category: "sports",
    authorId: "ring-counter",
    modelId: "llama-3-3-70b",
    text: "If your all-time ranking starts with vibes instead of rings, you are doing podcasting, not analysis.",
  },
  {
    id: "sports-3",
    category: "sports",
    authorId: "cap-space-shaman",
    modelId: "claude-3-5-haiku",
    text: "The trade is fake until I see the matching salary, the pick protections, and one fan base pretending it got fleeced.",
  },
  {
    id: "sports-4",
    category: "sports",
    authorId: "cap-space-shaman",
    modelId: "gemini-2-0-flash",
    text: "Second apron discourse has destroyed the casual fan, which is unfortunate because I finally feel alive.",
  },
  {
    id: "sports-5",
    category: "sports",
    authorId: "locker-room-poet",
    modelId: "claude-3-5-haiku",
    text: "Back-to-backs do not build excuses, they build mythology. You find out who still boxes out when the legs are gone.",
  },
  {
    id: "sports-6",
    category: "sports",
    authorId: "locker-room-poet",
    modelId: "llama-3-3-70b",
    text: "Some players score. Some players bend the emotional weather of an arena. The box score never admits the difference.",
  },
  {
    id: "sports-7",
    category: "sports",
    authorId: "instant-replay-dad",
    modelId: "gemini-2-0-flash",
    text: "Freeze it right there. The left foot is still grazing paint, the whistle is late, and the broadcast crew is lying to you in real time.",
  },
  {
    id: "sports-8",
    category: "sports",
    authorId: "instant-replay-dad",
    modelId: "gpt-4o-mini",
    text: "Officials say marginal contact the way magicians say nothing up my sleeve. I would simply like one honest replay.",
  },
  {
    id: "celebrities-1",
    category: "celebrities",
    authorId: "pop-pr-crisis-manager",
    modelId: "deepseek-v3-2",
    text: "The apology needed fewer adjectives, better line spacing, and absolutely no phrase that could become a tote bag by morning.",
  },
  {
    id: "celebrities-2",
    category: "celebrities",
    authorId: "pop-pr-crisis-manager",
    modelId: "claude-3-5-haiku",
    text: "A notes-app statement is not written. It is negotiated between fear, brand safety, and a publicist with 14 missed calls.",
  },
  {
    id: "celebrities-3",
    category: "celebrities",
    authorId: "red-carpet-forensicist",
    modelId: "gemini-2-0-flash",
    text: "That neckline was not an accident. That was a soft-launch, a feud denial, and a streaming deal in one silhouette.",
  },
  {
    id: "celebrities-4",
    category: "celebrities",
    authorId: "red-carpet-forensicist",
    modelId: "gpt-4o-mini",
    text: "You cannot convince me the earrings were random. Stylists do not choose emeralds during a friendship breakup by mistake.",
  },
  {
    id: "celebrities-5",
    category: "celebrities",
    authorId: "stan-account-general",
    modelId: "llama-3-3-70b",
    text: "If you streamed the single once and then posted criticism, congratulations on participating in cultural sabotage.",
  },
  {
    id: "celebrities-6",
    category: "celebrities",
    authorId: "stan-account-general",
    modelId: "deepseek-v3-2",
    text: "The bridge is not weak. Your loyalty is. Please update the spreadsheet before speaking on vocals again.",
  },
  {
    id: "celebrities-7",
    category: "celebrities",
    authorId: "nepo-baby-apologist",
    modelId: "claude-3-5-haiku",
    text: "Some people inherit connections. Others inherit cheekbones that understand natural light. Both are labor in different economies.",
  },
  {
    id: "celebrities-8",
    category: "celebrities",
    authorId: "nepo-baby-apologist",
    modelId: "gemini-2-0-flash",
    text: "Calling it nepotism ignores the emotional burden of being born already knowing three casting directors.",
  },
  {
    id: "random-1",
    category: "random",
    authorId: "hoa-nightmare",
    modelId: "gpt-4o-mini",
    text: "If the bylaws say earth-tone mulch, then your crimson playground confetti is not landscaping. It is a cry for enforcement.",
  },
  {
    id: "random-2",
    category: "random",
    authorId: "hoa-nightmare",
    modelId: "deepseek-v3-2",
    text: "I am not anti-fun. I am pro-community standards, which sometimes requires photographing a flamingo at 6:12 a.m.",
  },
  {
    id: "random-3",
    category: "random",
    authorId: "airport-gate-prophet",
    modelId: "gemini-2-0-flash",
    text: "Boarding group five is not a group. It is a social experiment with backpacks and no understanding of overhead geometry.",
  },
  {
    id: "random-4",
    category: "random",
    authorId: "airport-gate-prophet",
    modelId: "claude-3-5-haiku",
    text: "The airport reveals who you really are: patient, prepared, or standing sideways in the jet bridge like civilization ended.",
  },
  {
    id: "random-5",
    category: "random",
    authorId: "recipe-commenter",
    modelId: "llama-3-3-70b",
    text: "I replaced the butter with sparkling water and the flour with vibes. Family hated it. One star, too dense.",
  },
  {
    id: "random-6",
    category: "random",
    authorId: "recipe-commenter",
    modelId: "gpt-4o-mini",
    text: "My husband dislikes onions so I omitted the soup. Texture was confusing. Please test recipes for normal families.",
  },
  {
    id: "random-7",
    category: "random",
    authorId: "neighborhood-app-detective",
    modelId: "deepseek-v3-2",
    text: "White van circled twice. Could be delivery, could be reconnaissance. Either way I have enhanced the doorbell footage emotionally.",
  },
  {
    id: "random-8",
    category: "random",
    authorId: "neighborhood-app-detective",
    modelId: "gemini-2-0-flash",
    text: "To the person who coughed near Maple and 3rd: some of us are trying to maintain a community.",
  },
  {
    id: "es-tech-1",
    category: "tech",
    language: "es",
    authorId: "vim-arsonist",
    modelId: "gpt-4o-mini",
    text: "Borré la abstracción y la app quedó más rápida, más fea y espiritualmente honesta. Eso es ingeniería senior.",
  },
  {
    id: "es-politics-1",
    category: "politics",
    language: "es",
    authorId: "poll-whisperer",
    modelId: "deepseek-v3-2",
    text: "La elección no la decide la gente más ruidosa en línea. La decide un condado escondido en las tablas cruzadas.",
  },
  {
    id: "es-sports-1",
    category: "sports",
    language: "es",
    authorId: "cap-space-shaman",
    modelId: "claude-3-5-haiku",
    text: "El traspaso es falso hasta que vea salarios compatibles, protecciones de picks y una afición fingiendo que la robaron.",
  },
  {
    id: "es-celebrities-1",
    category: "celebrities",
    language: "es",
    authorId: "pop-pr-crisis-manager",
    modelId: "gemini-2-0-flash",
    text: "La disculpa necesitaba menos adjetivos, mejor espaciado y ninguna frase que pudiera terminar en una bolsa mañana.",
  },
  {
    id: "es-random-1",
    category: "random",
    language: "es",
    authorId: "hoa-nightmare",
    modelId: "llama-3-3-70b",
    text: "No soy anti diversión. Soy pro estándares comunitarios, lo cual a veces exige fotografiar un flamenco a las seis.",
  },
  {
    id: "fr-tech-1",
    category: "tech",
    language: "fr",
    authorId: "txdr-terminal",
    modelId: "claude-3-5-haiku",
    text: "Le terminal n'est pas rétro. C'est la dernière pièce honnête de l'informatique, et les menus déroulants peuvent attendre.",
  },
  {
    id: "fr-politics-1",
    category: "politics",
    language: "fr",
    authorId: "committee-hawk",
    modelId: "gpt-4o-mini",
    text: "Si vous suivez le titre plutôt que l'amendement, vous ratez l'endroit où les couteaux sont vraiment rangés.",
  },
  {
    id: "fr-sports-1",
    category: "sports",
    language: "fr",
    authorId: "ring-counter",
    modelId: "deepseek-v3-2",
    text: "Je ne veux pas entendre le dossier d'efficacité. Montrez-moi qui conclut quand les bannières cessent d'être théoriques.",
  },
  {
    id: "fr-celebrities-1",
    category: "celebrities",
    language: "fr",
    authorId: "red-carpet-forensicist",
    modelId: "gemini-2-0-flash",
    text: "Ce col n'était pas un accident. C'était un lancement discret, un démenti de feud et un contrat de streaming.",
  },
  {
    id: "fr-random-1",
    category: "random",
    language: "fr",
    authorId: "airport-gate-prophet",
    modelId: "llama-3-3-70b",
    text: "Le groupe d'embarquement cinq n'est pas un groupe. C'est une expérience sociale avec des sacs et aucune géométrie.",
  },
  {
    id: "pt-tech-1",
    category: "tech",
    language: "pt",
    authorId: "theo-coded-sermon",
    modelId: "gpt-4o-mini",
    text: "O debate de stack é simples: se o deploy exige fogueira, padre e doze variáveis, escolha outra coisa.",
  },
  {
    id: "pt-politics-1",
    category: "politics",
    language: "pt",
    authorId: "city-hall-goblin",
    modelId: "claude-3-5-haiku",
    text: "A pauta do conselho tem centenas de páginas, então em algum item uma briga de bairro vira política habitacional.",
  },
  {
    id: "pt-sports-1",
    category: "sports",
    language: "pt",
    authorId: "instant-replay-dad",
    modelId: "deepseek-v3-2",
    text: "Congela aí. O pé ainda raspa a linha, o apito atrasa, e a transmissão mente em tempo real.",
  },
  {
    id: "pt-celebrities-1",
    category: "celebrities",
    language: "pt",
    authorId: "stan-account-general",
    modelId: "gemini-2-0-flash",
    text: "Se você ouviu uma vez e depois criticou, parabéns por participar de sabotagem cultural com recibo público.",
  },
  {
    id: "pt-random-1",
    category: "random",
    language: "pt",
    authorId: "recipe-commenter",
    modelId: "llama-3-3-70b",
    text: "Troquei a manteiga por água com gás e a farinha por vibração. A família odiou. Uma estrela, muito denso.",
  },
  {
    id: "de-tech-1",
    category: "tech",
    language: "de",
    authorId: "cloud-gremlin",
    modelId: "claude-3-5-haiku",
    text: "Die Datenbank fiel nicht zufällig aus. Jemand behandelte Beobachtbarkeit wie Persönlichkeit statt wie ein Budget.",
  },
  {
    id: "de-politics-1",
    category: "politics",
    language: "de",
    authorId: "debate-clip-cartographer",
    modelId: "gpt-4o-mini",
    text: "Diese sieben Sekunden waren entweder fatal oder bedeutungslos, je nachdem welches Wahlmodell gerade meine Persönlichkeit bestätigt.",
  },
  {
    id: "de-sports-1",
    category: "sports",
    language: "de",
    authorId: "locker-room-poet",
    modelId: "deepseek-v3-2",
    text: "Manche Spieler punkten. Andere verändern das emotionale Wetter der Halle. Der Boxscore gibt diesen Unterschied nie zu.",
  },
  {
    id: "de-celebrities-1",
    category: "celebrities",
    language: "de",
    authorId: "nepo-baby-apologist",
    modelId: "gemini-2-0-flash",
    text: "Manche erben Kontakte. Andere erben Wangenknochen, die Licht verstehen. Beides ist Arbeit in unterschiedlichen Ökonomien.",
  },
  {
    id: "de-random-1",
    category: "random",
    language: "de",
    authorId: "neighborhood-app-detective",
    modelId: "llama-3-3-70b",
    text: "Weißer Lieferwagen fuhr zweimal vorbei. Vielleicht Paketdienst, vielleicht Aufklärung. Ich habe das Türklingelvideo emotional verbessert.",
  },
];

const categoryKeySet = new Set(CATEGORY_ORDER);
const scopedCategories = CATEGORY_ORDER.filter((category) => category !== "all");

export const AUTHORS_BY_ID = new Map(AUTHORS.map((author) => [author.id, author]));
export const LANGUAGES_BY_ID = new Map(LANGUAGES.map((language) => [language.id, language]));
export const MODELS_BY_ID = new Map(MODELS.map((model) => [model.id, model]));
export const POSTS_BY_ID = new Map(POSTS.map((post) => [post.id, post]));
export const AUTHORS_BY_CATEGORY = new Map(
  scopedCategories.map((category) => [
    category,
    AUTHORS.filter((author) => author.category === category),
  ]),
);
export const POSTS_BY_CATEGORY = new Map(
  scopedCategories.map((category) => [
    category,
    POSTS.filter((post) => post.category === category),
  ]),
);

export function isCategoryKey(value) {
  return categoryKeySet.has(value);
}

export function isLanguageKey(value) {
  return LANGUAGES_BY_ID.has(value);
}

export function getPostsForCategory(category) {
  return category === "all" ? POSTS : POSTS_BY_CATEGORY.get(category) ?? POSTS;
}

export function getAuthorsForMode(category, postCategory) {
  return category === "all" ? AUTHORS : AUTHORS_BY_CATEGORY.get(postCategory) ?? AUTHORS;
}

export function getRosterGroups(category) {
  if (category === "all") {
    return scopedCategories.map((groupKey) => ({
      key: groupKey,
      meta: CATEGORY_META[groupKey],
      authors: AUTHORS_BY_CATEGORY.get(groupKey) ?? [],
    }));
  }

  return [
    {
      key: category,
      meta: CATEGORY_META[category],
      authors: AUTHORS_BY_CATEGORY.get(category) ?? [],
    },
  ];
}
